
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  phone: 'phone',
  locale: 'locale',
  timezone: 'timezone',
  twoFactorEnabled: 'twoFactorEnabled',
  consentedAt: 'consentedAt',
  consentVersion: 'consentVersion',
  dataExportRequestedAt: 'dataExportRequestedAt',
  dataDeletionRequestedAt: 'dataDeletionRequestedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  token: 'token',
  expiresAt: 'expiresAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  activeOrganizationId: 'activeOrganizationId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  accountId: 'accountId',
  providerId: 'providerId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TwoFactorScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  secret: 'secret',
  backupCodes: 'backupCodes'
};

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  legalName: 'legalName',
  tradeName: 'tradeName',
  document: 'document',
  documentType: 'documentType',
  taxRegime: 'taxRegime',
  segmentType: 'segmentType',
  stockStructureType: 'stockStructureType',
  zipCode: 'zipCode',
  street: 'street',
  number: 'number',
  complement: 'complement',
  district: 'district',
  city: 'city',
  state: 'state',
  cnae: 'cnae',
  onboardingCompleted: 'onboardingCompleted',
  onboardingStep: 'onboardingStep',
  onboardingData: 'onboardingData',
  financeSettings: 'financeSettings',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MemberScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  role: 'role',
  locationScopes: 'locationScopes',
  channelScopes: 'channelScopes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvitationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  email: 'email',
  role: 'role',
  status: 'status',
  invitedById: 'invitedById',
  expiresAt: 'expiresAt',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrganizationCapabilityScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  key: 'key',
  value: 'value',
  config: 'config',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LocationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  type: 'type',
  isSelfService: 'isSelfService',
  is24h: 'is24h',
  zipCode: 'zipCode',
  street: 'street',
  number: 'number',
  complement: 'complement',
  district: 'district',
  city: 'city',
  state: 'state',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SalesChannelScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  type: 'type',
  name: 'name',
  config: 'config',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChannelLocationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  salesChannelId: 'salesChannelId',
  locationId: 'locationId',
  fulfillmentRank: 'fulfillmentRank',
  createdAt: 'createdAt'
};

exports.Prisma.SupplierScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  tradeName: 'tradeName',
  document: 'document',
  email: 'email',
  phone: 'phone',
  website: 'website',
  contactName: 'contactName',
  segment: 'segment',
  addressStreet: 'addressStreet',
  addressNumber: 'addressNumber',
  addressComplement: 'addressComplement',
  addressDistrict: 'addressDistrict',
  addressCity: 'addressCity',
  addressState: 'addressState',
  addressZip: 'addressZip',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  defaultPaymentTerms: 'defaultPaymentTerms',
  defaultLeadTimeDays: 'defaultLeadTimeDays',
  minOrderAmount: 'minOrderAmount',
  deliveryDays: 'deliveryDays',
  defaultDiscountPercent: 'defaultDiscountPercent',
  freightFixedAmount: 'freightFixedAmount',
  freightFreeAbove: 'freightFreeAbove',
  freightNotes: 'freightNotes',
  notes: 'notes'
};

exports.Prisma.SupplierAuditLogScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  supplierId: 'supplierId',
  userId: 'userId',
  userName: 'userName',
  action: 'action',
  changedFields: 'changedFields',
  createdAt: 'createdAt'
};

exports.Prisma.BrandScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  createdAt: 'createdAt'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  slug: 'slug',
  icon: 'icon',
  iconColor: 'iconColor',
  parentId: 'parentId',
  position: 'position',
  hasAgeRestriction: 'hasAgeRestriction',
  storageTemperature: 'storageTemperature',
  controlsExpiry: 'controlsExpiry',
  controlsLot: 'controlsLot',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  supplierId: 'supplierId',
  categoryId: 'categoryId',
  brandId: 'brandId',
  name: 'name',
  posName: 'posName',
  description: 'description',
  brand: 'brand',
  sku: 'sku',
  barcode: 'barcode',
  tags: 'tags',
  productType: 'productType',
  compositionKind: 'compositionKind',
  unit: 'unit',
  saleUnit: 'saleUnit',
  conversionFactor: 'conversionFactor',
  packUnit: 'packUnit',
  packSize: 'packSize',
  price: 'price',
  costPrice: 'costPrice',
  weight: 'weight',
  height: 'height',
  width: 'width',
  length: 'length',
  imageUrl: 'imageUrl',
  stockMin: 'stockMin',
  stockIdeal: 'stockIdeal',
  location: 'location',
  isActive: 'isActive',
  active: 'active',
  hasAgeRestriction: 'hasAgeRestriction',
  minAge: 'minAge',
  allowFractioned: 'allowFractioned',
  storageTemperature: 'storageTemperature',
  controlsExpiry: 'controlsExpiry',
  controlsLot: 'controlsLot',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductBarcodeScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  productId: 'productId',
  variantId: 'variantId',
  barcode: 'barcode',
  type: 'type',
  label: 'label',
  factor: 'factor',
  isDefault: 'isDefault',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductVariantScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  productId: 'productId',
  name: 'name',
  sku: 'sku',
  attributes: 'attributes',
  isActive: 'isActive',
  position: 'position',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductKitComponentScalarFieldEnum = {
  id: 'id',
  kitProductId: 'kitProductId',
  componentProductId: 'componentProductId',
  componentVariantId: 'componentVariantId',
  quantity: 'quantity',
  position: 'position',
  createdAt: 'createdAt'
};

exports.Prisma.ProductOptionGroupScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  productId: 'productId',
  name: 'name',
  unit: 'unit',
  required: 'required',
  minSelect: 'minSelect',
  maxSelect: 'maxSelect',
  position: 'position',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductOptionScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  componentProductId: 'componentProductId',
  componentVariantId: 'componentVariantId',
  name: 'name',
  quantity: 'quantity',
  priceDelta: 'priceDelta',
  isDefault: 'isDefault',
  position: 'position',
  createdAt: 'createdAt'
};

exports.Prisma.ProductPriceScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  productId: 'productId',
  variantId: 'variantId',
  locationId: 'locationId',
  channel: 'channel',
  price: 'price',
  promoPrice: 'promoPrice',
  cost: 'cost',
  validFrom: 'validFrom',
  validTo: 'validTo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductTaxScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  productId: 'productId',
  variantId: 'variantId',
  ncm: 'ncm',
  cest: 'cest',
  cfopInternal: 'cfopInternal',
  cfopInterstate: 'cfopInterstate',
  origin: 'origin',
  icmsCst: 'icmsCst',
  icmsCsosn: 'icmsCsosn',
  icmsRate: 'icmsRate',
  pisCst: 'pisCst',
  pisRate: 'pisRate',
  cofinsCst: 'cofinsCst',
  cofinsRate: 'cofinsRate',
  ipiCst: 'ipiCst',
  ipiRate: 'ipiRate',
  unitTaxable: 'unitTaxable',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategoryTaxDefaultScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  categoryId: 'categoryId',
  ncm: 'ncm',
  cest: 'cest',
  cfopInternal: 'cfopInternal',
  cfopInterstate: 'cfopInterstate',
  origin: 'origin',
  icmsCst: 'icmsCst',
  icmsCsosn: 'icmsCsosn',
  icmsRate: 'icmsRate',
  pisCst: 'pisCst',
  pisRate: 'pisRate',
  cofinsCst: 'cofinsCst',
  cofinsRate: 'cofinsRate',
  ipiCst: 'ipiCst',
  ipiRate: 'ipiRate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FiscalTemplateScalarFieldEnum = {
  id: 'id',
  segment: 'segment',
  productName: 'productName',
  barcode: 'barcode',
  suggestedNcm: 'suggestedNcm',
  suggestedCest: 'suggestedCest',
  defaultCfopInternal: 'defaultCfopInternal',
  defaultCfopInterstate: 'defaultCfopInterstate',
  icmsCst: 'icmsCst',
  icmsCsosn: 'icmsCsosn',
  pisCst: 'pisCst',
  cofinsCst: 'cofinsCst',
  origin: 'origin',
  description: 'description',
  createdAt: 'createdAt'
};

exports.Prisma.StockEntryScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  locationId: 'locationId',
  productId: 'productId',
  quantity: 'quantity',
  minQuantity: 'minQuantity',
  maxQuantity: 'maxQuantity',
  shelfLocation: 'shelfLocation',
  expiryDate: 'expiryDate',
  batchCode: 'batchCode',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
};

exports.Prisma.StockMovementScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  locationId: 'locationId',
  productId: 'productId',
  type: 'type',
  quantity: 'quantity',
  previousQty: 'previousQty',
  newQty: 'newQty',
  transferId: 'transferId',
  notes: 'notes',
  userId: 'userId',
  userName: 'userName',
  variantId: 'variantId',
  lotId: 'lotId',
  unitCost: 'unitCost',
  reason: 'reason',
  referenceType: 'referenceType',
  referenceId: 'referenceId',
  transferGroupId: 'transferGroupId',
  idempotencyKey: 'idempotencyKey',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.StockTransferScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  fromLocationId: 'fromLocationId',
  toLocationId: 'toLocationId',
  productId: 'productId',
  quantity: 'quantity',
  notes: 'notes',
  status: 'status',
  userId: 'userId',
  userName: 'userName',
  createdAt: 'createdAt'
};

exports.Prisma.StockLotScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  productId: 'productId',
  variantId: 'variantId',
  code: 'code',
  expiryDate: 'expiryDate',
  manufactureDate: 'manufactureDate',
  receivedAt: 'receivedAt',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StockBalanceScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  productId: 'productId',
  variantId: 'variantId',
  locationId: 'locationId',
  lotId: 'lotId',
  quantityOnHand: 'quantityOnHand',
  quantityReserved: 'quantityReserved',
  averageCost: 'averageCost',
  minQuantity: 'minQuantity',
  idealQuantity: 'idealQuantity',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
};

exports.Prisma.StockReservationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  productId: 'productId',
  variantId: 'variantId',
  locationId: 'locationId',
  lotId: 'lotId',
  quantity: 'quantity',
  referenceType: 'referenceType',
  referenceId: 'referenceId',
  status: 'status',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  resolvedAt: 'resolvedAt'
};

exports.Prisma.InventoryCountScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  locationId: 'locationId',
  status: 'status',
  startedBy: 'startedBy',
  note: 'note',
  startedAt: 'startedAt',
  closedAt: 'closedAt'
};

exports.Prisma.InventoryCountItemScalarFieldEnum = {
  id: 'id',
  countId: 'countId',
  productId: 'productId',
  variantId: 'variantId',
  lotId: 'lotId',
  systemQuantity: 'systemQuantity',
  countedQuantity: 'countedQuantity',
  adjustmentMovementId: 'adjustmentMovementId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserPreferencesScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  activeScopeType: 'activeScopeType',
  activeScopeId: 'activeScopeId',
  theme: 'theme',
  locale: 'locale',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  actorId: 'actorId',
  action: 'action',
  resourceType: 'resourceType',
  resourceId: 'resourceId',
  before: 'before',
  after: 'after',
  metadata: 'metadata',
  ipAddress: 'ipAddress',
  createdAt: 'createdAt'
};

exports.Prisma.CustomerScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  personType: 'personType',
  name: 'name',
  document: 'document',
  phone: 'phone',
  whatsapp: 'whatsapp',
  email: 'email',
  contactName: 'contactName',
  addressStreet: 'addressStreet',
  addressNumber: 'addressNumber',
  addressComplement: 'addressComplement',
  addressDistrict: 'addressDistrict',
  addressCity: 'addressCity',
  addressState: 'addressState',
  addressZip: 'addressZip',
  notes: 'notes',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomerAuditLogScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  customerId: 'customerId',
  userId: 'userId',
  userName: 'userName',
  action: 'action',
  changedFields: 'changedFields',
  createdAt: 'createdAt'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  locationId: 'locationId',
  channel: 'channel',
  status: 'status',
  customerId: 'customerId',
  cashSessionId: 'cashSessionId',
  subtotal: 'subtotal',
  discountTotal: 'discountTotal',
  total: 'total',
  idempotencyKey: 'idempotencyKey',
  externalId: 'externalId',
  channelMetadata: 'channelMetadata',
  canceledReason: 'canceledReason',
  canceledAt: 'canceledAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  variantId: 'variantId',
  productNameSnapshot: 'productNameSnapshot',
  skuSnapshot: 'skuSnapshot',
  unitSnapshot: 'unitSnapshot',
  unitPriceSnapshot: 'unitPriceSnapshot',
  costSnapshot: 'costSnapshot',
  taxSnapshot: 'taxSnapshot',
  productTypeSnapshot: 'productTypeSnapshot',
  quantity: 'quantity',
  discountAmount: 'discountAmount',
  lineTotal: 'lineTotal',
  isKit: 'isKit',
  createdAt: 'createdAt'
};

exports.Prisma.OrderItemSelectionScalarFieldEnum = {
  id: 'id',
  orderItemId: 'orderItemId',
  groupId: 'groupId',
  optionId: 'optionId',
  componentProductId: 'componentProductId',
  componentVariantId: 'componentVariantId',
  groupNameSnapshot: 'groupNameSnapshot',
  optionNameSnapshot: 'optionNameSnapshot',
  quantitySnapshot: 'quantitySnapshot',
  priceDeltaSnapshot: 'priceDeltaSnapshot',
  createdAt: 'createdAt'
};

exports.Prisma.OrderStatusHistoryScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  fromStatus: 'fromStatus',
  toStatus: 'toStatus',
  actorId: 'actorId',
  source: 'source',
  reason: 'reason',
  createdAt: 'createdAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  method: 'method',
  provider: 'provider',
  amount: 'amount',
  receivedAmount: 'receivedAmount',
  changeAmount: 'changeAmount',
  status: 'status',
  externalPaymentId: 'externalPaymentId',
  pixQrCode: 'pixQrCode',
  pixQrCodeUrl: 'pixQrCodeUrl',
  pixExpiresAt: 'pixExpiresAt',
  confirmedAt: 'confirmedAt',
  failedAt: 'failedAt',
  refundedAt: 'refundedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CashSessionScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  locationId: 'locationId',
  operatorId: 'operatorId',
  status: 'status',
  openingAmount: 'openingAmount',
  closingAmount: 'closingAmount',
  systemAmount: 'systemAmount',
  divergence: 'divergence',
  openedAt: 'openedAt',
  closedAt: 'closedAt',
  note: 'note'
};

exports.Prisma.CashMovementScalarFieldEnum = {
  id: 'id',
  cashSessionId: 'cashSessionId',
  type: 'type',
  amount: 'amount',
  note: 'note',
  actorId: 'actorId',
  categoryId: 'categoryId',
  createdAt: 'createdAt'
};

exports.Prisma.ChannelIntegrationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  channel: 'channel',
  status: 'status',
  credentials: 'credentials',
  settings: 'settings',
  lastSyncAt: 'lastSyncAt',
  lastErrorAt: 'lastErrorAt',
  lastErrorMsg: 'lastErrorMsg',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChannelProductMappingScalarFieldEnum = {
  id: 'id',
  channelIntegrationId: 'channelIntegrationId',
  organizationId: 'organizationId',
  productId: 'productId',
  variantId: 'variantId',
  channel: 'channel',
  externalId: 'externalId',
  externalSku: 'externalSku',
  syncedAt: 'syncedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OutboxEventScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  aggregateType: 'aggregateType',
  aggregateId: 'aggregateId',
  eventType: 'eventType',
  payload: 'payload',
  status: 'status',
  priority: 'priority',
  attempts: 'attempts',
  maxAttempts: 'maxAttempts',
  nextRetryAt: 'nextRetryAt',
  processedAt: 'processedAt',
  lastError: 'lastError',
  idempotencyKey: 'idempotencyKey',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InboundEventScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  channel: 'channel',
  externalEventId: 'externalEventId',
  eventType: 'eventType',
  payload: 'payload',
  processedAt: 'processedAt',
  errorMsg: 'errorMsg',
  createdAt: 'createdAt'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  locationId: 'locationId',
  orderId: 'orderId',
  customerId: 'customerId',
  type: 'type',
  status: 'status',
  series: 'series',
  number: 'number',
  accessKey: 'accessKey',
  protocol: 'protocol',
  issuedAt: 'issuedAt',
  authorizedAt: 'authorizedAt',
  canceledAt: 'canceledAt',
  totalAmount: 'totalAmount',
  totalTax: 'totalTax',
  provider: 'provider',
  providerInvoiceId: 'providerInvoiceId',
  xmlIssued: 'xmlIssued',
  xmlCanceled: 'xmlCanceled',
  qrCode: 'qrCode',
  danfeUrl: 'danfeUrl',
  rejectionReason: 'rejectionReason',
  rejectionCode: 'rejectionCode',
  cancelReason: 'cancelReason',
  cancelDeadline: 'cancelDeadline',
  contingencyMode: 'contingencyMode',
  idempotencyKey: 'idempotencyKey',
  attemptCount: 'attemptCount',
  lastAttemptAt: 'lastAttemptAt',
  nextRetryAt: 'nextRetryAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceEventScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  eventType: 'eventType',
  fromStatus: 'fromStatus',
  toStatus: 'toStatus',
  actorId: 'actorId',
  source: 'source',
  providerResponse: 'providerResponse',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.FiscalCertificateScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  subject: 'subject',
  validFrom: 'validFrom',
  validTo: 'validTo',
  encryptedPfx: 'encryptedPfx',
  encryptedPassword: 'encryptedPassword',
  iv: 'iv',
  isActive: 'isActive',
  uploadedBy: 'uploadedBy',
  uploadedAt: 'uploadedAt',
  revokedAt: 'revokedAt',
  revokedBy: 'revokedBy'
};

exports.Prisma.FiscalConfigScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  environment: 'environment',
  provider: 'provider',
  nfceSeries: 'nfceSeries',
  nfceCscId: 'nfceCscId',
  nfceCscToken: 'nfceCscToken',
  providerCredentials: 'providerCredentials',
  homologationTestedAt: 'homologationTestedAt',
  promotedAt: 'promotedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceNumberSkipScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  series: 'series',
  numberStart: 'numberStart',
  numberEnd: 'numberEnd',
  reason: 'reason',
  status: 'status',
  requestedBy: 'requestedBy',
  requestedAt: 'requestedAt',
  processedAt: 'processedAt',
  providerResponse: 'providerResponse'
};

exports.Prisma.SupplierProductMappingScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  supplierId: 'supplierId',
  supplierProductCode: 'supplierProductCode',
  supplierProductName: 'supplierProductName',
  productId: 'productId',
  variantId: 'variantId',
  defaultPackQuantity: 'defaultPackQuantity',
  purchaseUnit: 'purchaseUnit',
  minOrderQuantity: 'minOrderQuantity',
  barcode: 'barcode',
  leadTimeDays: 'leadTimeDays',
  discountPercent: 'discountPercent',
  lastCost: 'lastCost',
  previousCost: 'previousCost',
  lastPurchaseAt: 'lastPurchaseAt',
  isPreferred: 'isPreferred',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupplierProductPriceHistoryScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  mappingId: 'mappingId',
  unitCost: 'unitCost',
  source: 'source',
  sourceId: 'sourceId',
  recordedAt: 'recordedAt'
};

exports.Prisma.PurchaseOrderScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  supplierId: 'supplierId',
  locationId: 'locationId',
  status: 'status',
  number: 'number',
  paymentTerms: 'paymentTerms',
  expectedDate: 'expectedDate',
  confirmedDate: 'confirmedDate',
  notes: 'notes',
  subtotal: 'subtotal',
  discountTotal: 'discountTotal',
  freight: 'freight',
  total: 'total',
  originSuggestionId: 'originSuggestionId',
  originQuotationId: 'originQuotationId',
  idempotencyKey: 'idempotencyKey',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PurchaseOrderItemScalarFieldEnum = {
  id: 'id',
  purchaseOrderId: 'purchaseOrderId',
  productId: 'productId',
  variantId: 'variantId',
  productNameSnapshot: 'productNameSnapshot',
  expectedQuantity: 'expectedQuantity',
  unitCost: 'unitCost',
  lineTotal: 'lineTotal',
  fiscalDataSnapshot: 'fiscalDataSnapshot',
  expectedPackQuantity: 'expectedPackQuantity',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PurchaseOrderStatusHistoryScalarFieldEnum = {
  id: 'id',
  purchaseOrderId: 'purchaseOrderId',
  fromStatus: 'fromStatus',
  toStatus: 'toStatus',
  actorId: 'actorId',
  source: 'source',
  reason: 'reason',
  createdAt: 'createdAt'
};

exports.Prisma.GoodsReceiptScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  purchaseOrderId: 'purchaseOrderId',
  receivedAt: 'receivedAt',
  receivedBy: 'receivedBy',
  supplierInvoiceNumber: 'supplierInvoiceNumber',
  supplierInvoiceSeries: 'supplierInvoiceSeries',
  supplierInvoiceAccessKey: 'supplierInvoiceAccessKey',
  status: 'status',
  notes: 'notes',
  divergenceSummary: 'divergenceSummary',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GoodsReceiptItemScalarFieldEnum = {
  id: 'id',
  goodsReceiptId: 'goodsReceiptId',
  purchaseOrderItemId: 'purchaseOrderItemId',
  productId: 'productId',
  variantId: 'variantId',
  lotCode: 'lotCode',
  expiryDate: 'expiryDate',
  receivedQuantity: 'receivedQuantity',
  unitCost: 'unitCost',
  divergence: 'divergence',
  divergenceNote: 'divergenceNote',
  stockMovementId: 'stockMovementId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupplierReturnScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  goodsReceiptId: 'goodsReceiptId',
  supplierId: 'supplierId',
  reason: 'reason',
  status: 'status',
  returnedAt: 'returnedAt',
  returnedBy: 'returnedBy',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupplierReturnItemScalarFieldEnum = {
  id: 'id',
  supplierReturnId: 'supplierReturnId',
  goodsReceiptItemId: 'goodsReceiptItemId',
  quantity: 'quantity',
  unitCost: 'unitCost',
  stockMovementId: 'stockMovementId',
  accountPayableAdjustmentId: 'accountPayableAdjustmentId'
};

exports.Prisma.AccountPayableScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  supplierId: 'supplierId',
  goodsReceiptId: 'goodsReceiptId',
  purchaseOrderId: 'purchaseOrderId',
  amount: 'amount',
  paidAmount: 'paidAmount',
  dueDate: 'dueDate',
  status: 'status',
  description: 'description',
  installmentNumber: 'installmentNumber',
  totalInstallments: 'totalInstallments',
  categoryId: 'categoryId',
  paidAt: 'paidAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountReceivableScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  customerId: 'customerId',
  orderId: 'orderId',
  amount: 'amount',
  receivedAmount: 'receivedAmount',
  dueDate: 'dueDate',
  status: 'status',
  description: 'description',
  installmentNumber: 'installmentNumber',
  totalInstallments: 'totalInstallments',
  categoryId: 'categoryId',
  receivedAt: 'receivedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentSettlementScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  paymentId: 'paymentId',
  provider: 'provider',
  grossAmount: 'grossAmount',
  feeAmount: 'feeAmount',
  netAmount: 'netAmount',
  expectedDate: 'expectedDate',
  settledAt: 'settledAt',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FinanceCategoryScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  kind: 'kind',
  archived: 'archived',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.QuotationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  description: 'description',
  status: 'status',
  expectedDeliveryDate: 'expectedDeliveryDate',
  createdBy: 'createdBy',
  closedAt: 'closedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.QuotationItemScalarFieldEnum = {
  id: 'id',
  quotationId: 'quotationId',
  productId: 'productId',
  variantId: 'variantId',
  quantity: 'quantity',
  notes: 'notes'
};

exports.Prisma.QuotationSupplierResponseScalarFieldEnum = {
  id: 'id',
  quotationId: 'quotationId',
  supplierId: 'supplierId',
  totalPrice: 'totalPrice',
  paymentTerms: 'paymentTerms',
  leadTimeDays: 'leadTimeDays',
  notes: 'notes',
  receivedAt: 'receivedAt',
  selected: 'selected'
};

exports.Prisma.QuotationSupplierItemResponseScalarFieldEnum = {
  id: 'id',
  quotationSupplierResponseId: 'quotationSupplierResponseId',
  quotationItemId: 'quotationItemId',
  unitCost: 'unitCost',
  available: 'available',
  notes: 'notes'
};

exports.Prisma.PurchaseSuggestionScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  locationId: 'locationId',
  generatedAt: 'generatedAt',
  status: 'status',
  algorithmVersion: 'algorithmVersion',
  reasonSummary: 'reasonSummary'
};

exports.Prisma.PurchaseSuggestionItemScalarFieldEnum = {
  id: 'id',
  purchaseSuggestionId: 'purchaseSuggestionId',
  productId: 'productId',
  variantId: 'variantId',
  suggestedQuantity: 'suggestedQuantity',
  currentStock: 'currentStock',
  averageDailySales: 'averageDailySales',
  daysOfCoverage: 'daysOfCoverage',
  suggestedSupplierId: 'suggestedSupplierId'
};

exports.Prisma.NfeImportScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  accessKey: 'accessKey',
  xmlContent: 'xmlContent',
  status: 'status',
  uploadedBy: 'uploadedBy',
  uploadedAt: 'uploadedAt',
  supplierId: 'supplierId',
  purchaseOrderId: 'purchaseOrderId',
  goodsReceiptId: 'goodsReceiptId',
  parseErrors: 'parseErrors',
  parsedData: 'parsedData',
  mappingPending: 'mappingPending',
  updatedAt: 'updatedAt'
};

exports.Prisma.TagScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  slug: 'slug',
  group: 'group',
  color: 'color',
  description: 'description',
  scope: 'scope',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductTagScalarFieldEnum = {
  productId: 'productId',
  tagId: 'tagId',
  assignedAt: 'assignedAt'
};

exports.Prisma.CategoryTagScalarFieldEnum = {
  categoryId: 'categoryId',
  tagId: 'tagId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.DocumentType = exports.$Enums.DocumentType = {
  CNPJ: 'CNPJ',
  CPF: 'CPF'
};

exports.TaxRegime = exports.$Enums.TaxRegime = {
  SIMPLES_NACIONAL: 'SIMPLES_NACIONAL',
  LUCRO_PRESUMIDO: 'LUCRO_PRESUMIDO',
  LUCRO_REAL: 'LUCRO_REAL',
  MEI: 'MEI'
};

exports.SegmentType = exports.$Enums.SegmentType = {
  BEVERAGE_CONVENIENCE: 'BEVERAGE_CONVENIENCE',
  SUPERMARKET: 'SUPERMARKET',
  UNMANNED_MARKET: 'UNMANNED_MARKET'
};

exports.StockStructureType = exports.$Enums.StockStructureType = {
  LOCAL: 'LOCAL',
  CENTRAL_DC: 'CENTRAL_DC',
  HYBRID: 'HYBRID'
};

exports.MemberRole = exports.$Enums.MemberRole = {
  owner: 'owner',
  admin: 'admin',
  manager: 'manager',
  operator: 'operator',
  viewer: 'viewer'
};

exports.InvitationStatus = exports.$Enums.InvitationStatus = {
  pending: 'pending',
  accepted: 'accepted',
  expired: 'expired',
  revoked: 'revoked'
};

exports.LocationType = exports.$Enums.LocationType = {
  STORE: 'STORE',
  DC: 'DC',
  HYBRID: 'HYBRID',
  WAREHOUSE: 'WAREHOUSE',
  DARK_STORE: 'DARK_STORE'
};

exports.SalesChannelType = exports.$Enums.SalesChannelType = {
  IFOOD: 'IFOOD',
  WHATSAPP: 'WHATSAPP',
  MERCADO_LIVRE: 'MERCADO_LIVRE',
  RAPPI: 'RAPPI',
  OWN_ECOMMERCE: 'OWN_ECOMMERCE',
  OTHER: 'OTHER'
};

exports.StorageTemperature = exports.$Enums.StorageTemperature = {
  AMBIENTE: 'AMBIENTE',
  REFRIGERADO: 'REFRIGERADO',
  CONGELADO: 'CONGELADO'
};

exports.ProductType = exports.$Enums.ProductType = {
  SIMPLE: 'SIMPLE',
  VARIANT_PARENT: 'VARIANT_PARENT',
  KIT: 'KIT',
  FRACTIONED: 'FRACTIONED',
  CUSTOM: 'CUSTOM'
};

exports.CompositionKind = exports.$Enums.CompositionKind = {
  COMBO: 'COMBO',
  RECIPE: 'RECIPE'
};

exports.ProductUnit = exports.$Enums.ProductUnit = {
  UN: 'UN',
  KG: 'KG',
  G: 'G',
  L: 'L',
  ML: 'ML',
  CX: 'CX',
  PCT: 'PCT',
  FARDO: 'FARDO',
  DZ: 'DZ',
  BANDEJA: 'BANDEJA',
  CENTO: 'CENTO'
};

exports.ProductBarcodeType = exports.$Enums.ProductBarcodeType = {
  EAN13: 'EAN13',
  EAN8: 'EAN8',
  INTERNAL: 'INTERNAL',
  DUN14: 'DUN14'
};

exports.TaxOrigin = exports.$Enums.TaxOrigin = {
  NACIONAL: 'NACIONAL',
  IMPORTADO_DIRETO: 'IMPORTADO_DIRETO',
  IMPORTADO_NACIONAL: 'IMPORTADO_NACIONAL',
  NACIONAL_MAIS_40_IMPORTADO: 'NACIONAL_MAIS_40_IMPORTADO',
  NACIONAL_MENOS_40_IMPORTADO: 'NACIONAL_MENOS_40_IMPORTADO',
  NACIONAL_SEM_SIMILAR: 'NACIONAL_SEM_SIMILAR',
  ESTRANGEIRO_DIRETO: 'ESTRANGEIRO_DIRETO',
  ESTRANGEIRO_NACIONAL: 'ESTRANGEIRO_NACIONAL',
  NACIONAL_MENOS_70_IMPORTADO: 'NACIONAL_MENOS_70_IMPORTADO'
};

exports.FiscalSegment = exports.$Enums.FiscalSegment = {
  BEVERAGE: 'BEVERAGE',
  CONVENIENCE: 'CONVENIENCE',
  SNACK: 'SNACK',
  DAIRY: 'DAIRY',
  BAKERY: 'BAKERY',
  MEAT: 'MEAT',
  FROZEN: 'FROZEN',
  CLEANING: 'CLEANING',
  PERSONAL_HYGIENE: 'PERSONAL_HYGIENE',
  OTHER: 'OTHER'
};

exports.MovementType = exports.$Enums.MovementType = {
  IN: 'IN',
  OUT: 'OUT',
  LOSS: 'LOSS',
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  ADJUSTMENT: 'ADJUSTMENT',
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
  RESERVATION: 'RESERVATION',
  RESERVATION_RELEASE: 'RESERVATION_RELEASE'
};

exports.MovementReason = exports.$Enums.MovementReason = {
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  INVENTORY_COUNT: 'INVENTORY_COUNT',
  DAMAGE: 'DAMAGE',
  EXPIRY: 'EXPIRY',
  THEFT: 'THEFT',
  TRANSFER: 'TRANSFER',
  MANUAL: 'MANUAL',
  RETURN: 'RETURN',
  INITIAL: 'INITIAL'
};

exports.ReservationStatus = exports.$Enums.ReservationStatus = {
  ACTIVE: 'ACTIVE',
  CONSUMED: 'CONSUMED',
  RELEASED: 'RELEASED',
  EXPIRED: 'EXPIRED'
};

exports.InventoryCountStatus = exports.$Enums.InventoryCountStatus = {
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  CLOSED: 'CLOSED'
};

exports.OrderChannel = exports.$Enums.OrderChannel = {
  POS: 'POS',
  SELF_SERVICE: 'SELF_SERVICE',
  IFOOD: 'IFOOD',
  WHATSAPP: 'WHATSAPP',
  MERCADO_LIVRE: 'MERCADO_LIVRE'
};

exports.OrderStatus = exports.$Enums.OrderStatus = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  PAID: 'PAID',
  FULFILLED: 'FULFILLED',
  COMPLETED: 'COMPLETED',
  CANCELED: 'CANCELED'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CASH: 'CASH',
  PIX_MANUAL: 'PIX_MANUAL',
  PIX_DYNAMIC: 'PIX_DYNAMIC',
  CARD_PRESENT: 'CARD_PRESENT',
  CARD_CREDIT: 'CARD_CREDIT',
  CARD_DEBIT: 'CARD_DEBIT',
  CARD_ONLINE: 'CARD_ONLINE',
  VOUCHER: 'VOUCHER'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED'
};

exports.CashSessionStatus = exports.$Enums.CashSessionStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED'
};

exports.CashMovementType = exports.$Enums.CashMovementType = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE',
  BLEED: 'BLEED',
  SUPPLY: 'SUPPLY'
};

exports.ChannelStatus = exports.$Enums.ChannelStatus = {
  DISCONNECTED: 'DISCONNECTED',
  CONNECTED: 'CONNECTED',
  ERROR: 'ERROR'
};

exports.OutboxStatus = exports.$Enums.OutboxStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  DONE: 'DONE',
  FAILED: 'FAILED',
  DEAD: 'DEAD'
};

exports.InvoiceType = exports.$Enums.InvoiceType = {
  NFCE: 'NFCE'
};

exports.InvoiceStatus = exports.$Enums.InvoiceStatus = {
  PENDING: 'PENDING',
  SENDING: 'SENDING',
  IN_CONTINGENCY: 'IN_CONTINGENCY',
  AUTHORIZED: 'AUTHORIZED',
  REJECTED: 'REJECTED',
  DENIED: 'DENIED',
  CANCELED: 'CANCELED'
};

exports.FiscalProviderEnum = exports.$Enums.FiscalProviderEnum = {
  FOCUS_NFE: 'FOCUS_NFE',
  TECNOSPEED: 'TECNOSPEED'
};

exports.ContingencyMode = exports.$Enums.ContingencyMode = {
  EPEC: 'EPEC',
  SVC: 'SVC'
};

exports.InvoiceEventType = exports.$Enums.InvoiceEventType = {
  SUBMITTED: 'SUBMITTED',
  AUTHORIZED: 'AUTHORIZED',
  REJECTED: 'REJECTED',
  DENIED: 'DENIED',
  CONTINGENCY_ENTERED: 'CONTINGENCY_ENTERED',
  CONTINGENCY_TRANSMITTED: 'CONTINGENCY_TRANSMITTED',
  CANCEL_REQUESTED: 'CANCEL_REQUESTED',
  CANCELED: 'CANCELED',
  INUTILIZED: 'INUTILIZED',
  RETRY_SCHEDULED: 'RETRY_SCHEDULED'
};

exports.InvoiceEventSource = exports.$Enums.InvoiceEventSource = {
  INTERNAL: 'INTERNAL',
  WORKER: 'WORKER',
  PROVIDER_WEBHOOK: 'PROVIDER_WEBHOOK',
  MANUAL: 'MANUAL'
};

exports.FiscalEnvironment = exports.$Enums.FiscalEnvironment = {
  HOMOLOGATION: 'HOMOLOGATION',
  PRODUCTION: 'PRODUCTION'
};

exports.NumberSkipStatus = exports.$Enums.NumberSkipStatus = {
  REQUESTED: 'REQUESTED',
  INUTILIZED: 'INUTILIZED',
  REJECTED: 'REJECTED'
};

exports.PriceSource = exports.$Enums.PriceSource = {
  PURCHASE_ORDER: 'PURCHASE_ORDER',
  GOODS_RECEIPT: 'GOODS_RECEIPT',
  NFE_IMPORT: 'NFE_IMPORT',
  MANUAL: 'MANUAL'
};

exports.PurchaseOrderStatus = exports.$Enums.PurchaseOrderStatus = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  CONFIRMED: 'CONFIRMED',
  RECEIVING: 'RECEIVING',
  RECEIVED: 'RECEIVED',
  CANCELED: 'CANCELED'
};

exports.PoHistorySource = exports.$Enums.PoHistorySource = {
  INTERNAL: 'INTERNAL',
  XML_IMPORT: 'XML_IMPORT',
  MANUAL: 'MANUAL'
};

exports.GoodsReceiptStatus = exports.$Enums.GoodsReceiptStatus = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  CANCELED: 'CANCELED'
};

exports.DivergenceType = exports.$Enums.DivergenceType = {
  NONE: 'NONE',
  QUANTITY: 'QUANTITY',
  COST: 'COST',
  QUALITY: 'QUALITY'
};

exports.SupplierReturnReason = exports.$Enums.SupplierReturnReason = {
  DEFECT: 'DEFECT',
  EXPIRY: 'EXPIRY',
  WRONG_ITEM: 'WRONG_ITEM',
  OVERSTOCK: 'OVERSTOCK',
  OTHER: 'OTHER'
};

exports.SupplierReturnStatus = exports.$Enums.SupplierReturnStatus = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  CANCELED: 'CANCELED'
};

exports.AccountPayableStatus = exports.$Enums.AccountPayableStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  CANCELED: 'CANCELED'
};

exports.AccountReceivableStatus = exports.$Enums.AccountReceivableStatus = {
  PENDING: 'PENDING',
  PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
  RECEIVED: 'RECEIVED',
  CANCELED: 'CANCELED'
};

exports.SettlementStatus = exports.$Enums.SettlementStatus = {
  PENDING: 'PENDING',
  SETTLED: 'SETTLED',
  CANCELED: 'CANCELED'
};

exports.FinanceCategoryKind = exports.$Enums.FinanceCategoryKind = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE'
};

exports.QuotationStatus = exports.$Enums.QuotationStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  CONVERTED: 'CONVERTED'
};

exports.PurchaseSuggestionStatus = exports.$Enums.PurchaseSuggestionStatus = {
  PENDING: 'PENDING',
  CONVERTED: 'CONVERTED',
  DISMISSED: 'DISMISSED'
};

exports.NfeImportStatus = exports.$Enums.NfeImportStatus = {
  PENDING: 'PENDING',
  PARSED: 'PARSED',
  MAPPED: 'MAPPED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED'
};

exports.TagScope = exports.$Enums.TagScope = {
  SUBCATEGORY: 'SUBCATEGORY',
  PRODUCT: 'PRODUCT'
};

exports.Prisma.ModelName = {
  User: 'User',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification',
  TwoFactor: 'TwoFactor',
  Organization: 'Organization',
  Member: 'Member',
  Invitation: 'Invitation',
  OrganizationCapability: 'OrganizationCapability',
  Location: 'Location',
  SalesChannel: 'SalesChannel',
  ChannelLocation: 'ChannelLocation',
  Supplier: 'Supplier',
  SupplierAuditLog: 'SupplierAuditLog',
  Brand: 'Brand',
  Category: 'Category',
  Product: 'Product',
  ProductBarcode: 'ProductBarcode',
  ProductVariant: 'ProductVariant',
  ProductKitComponent: 'ProductKitComponent',
  ProductOptionGroup: 'ProductOptionGroup',
  ProductOption: 'ProductOption',
  ProductPrice: 'ProductPrice',
  ProductTax: 'ProductTax',
  CategoryTaxDefault: 'CategoryTaxDefault',
  FiscalTemplate: 'FiscalTemplate',
  StockEntry: 'StockEntry',
  StockMovement: 'StockMovement',
  StockTransfer: 'StockTransfer',
  StockLot: 'StockLot',
  StockBalance: 'StockBalance',
  StockReservation: 'StockReservation',
  InventoryCount: 'InventoryCount',
  InventoryCountItem: 'InventoryCountItem',
  UserPreferences: 'UserPreferences',
  AuditLog: 'AuditLog',
  Customer: 'Customer',
  CustomerAuditLog: 'CustomerAuditLog',
  Order: 'Order',
  OrderItem: 'OrderItem',
  OrderItemSelection: 'OrderItemSelection',
  OrderStatusHistory: 'OrderStatusHistory',
  Payment: 'Payment',
  CashSession: 'CashSession',
  CashMovement: 'CashMovement',
  ChannelIntegration: 'ChannelIntegration',
  ChannelProductMapping: 'ChannelProductMapping',
  OutboxEvent: 'OutboxEvent',
  InboundEvent: 'InboundEvent',
  Invoice: 'Invoice',
  InvoiceEvent: 'InvoiceEvent',
  FiscalCertificate: 'FiscalCertificate',
  FiscalConfig: 'FiscalConfig',
  InvoiceNumberSkip: 'InvoiceNumberSkip',
  SupplierProductMapping: 'SupplierProductMapping',
  SupplierProductPriceHistory: 'SupplierProductPriceHistory',
  PurchaseOrder: 'PurchaseOrder',
  PurchaseOrderItem: 'PurchaseOrderItem',
  PurchaseOrderStatusHistory: 'PurchaseOrderStatusHistory',
  GoodsReceipt: 'GoodsReceipt',
  GoodsReceiptItem: 'GoodsReceiptItem',
  SupplierReturn: 'SupplierReturn',
  SupplierReturnItem: 'SupplierReturnItem',
  AccountPayable: 'AccountPayable',
  AccountReceivable: 'AccountReceivable',
  PaymentSettlement: 'PaymentSettlement',
  FinanceCategory: 'FinanceCategory',
  Quotation: 'Quotation',
  QuotationItem: 'QuotationItem',
  QuotationSupplierResponse: 'QuotationSupplierResponse',
  QuotationSupplierItemResponse: 'QuotationSupplierItemResponse',
  PurchaseSuggestion: 'PurchaseSuggestion',
  PurchaseSuggestionItem: 'PurchaseSuggestionItem',
  NfeImport: 'NfeImport',
  Tag: 'Tag',
  ProductTag: 'ProductTag',
  CategoryTag: 'CategoryTag'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
